### ISSUE TITLE
[Presence | Bug] YouTube Music

### ISSUE THREAD

**Issue by ACertainCoder** [PreMiD/Presences#3735]
**Describe the Bug**
When the current song changes automatically (in a playlist for example), the presence starts showing invalid data about the remaining time.

**Steps to Reproduce**
1. Login with an account that has YT Music **Premium**
2. Start listening to a playlist
3. Wait until the song you've selected has less than 10 seconds left
4. Take a look at the presence

**Expected Behavior**
It should still display correct information about the remaining time.

**Screenshots / Videos**
Please read the additional context first.
https://cdn.discordapp.com/attachments/534018310128402435/842859759321088071/2021-05-14_22-18-13.mp4

**Environment**
- OS: Windows 10 20H2
- Browser: Firefox / Edge
- Version: 88.0.1 (64-Bit) / 90.0 (64-Bit)

**Additional context**
I opened an issue a while ago and haven't had time to address the problem until now. This time with more information tho:
The YT Music presence gets its information from the video container. The issue with this is, that YouTube caches already played songs and preloads the next song **if you have a premium subscription**. This can be avoided by simply using the process-bar container instead.

You can use this script to check the state of the video (cache) - and process bar container.
```js
setInterval(function() {
    const video = document.querySelector("video");
    const bar = document.querySelector("#progress-bar");

    console.clear();
    console.log(`Cache: ${video.currentTime} / ${video.duration}`);
    console.log(`Progress: ${bar.value} / ${bar.max}`);
}, 1000);
```

**Original issue**
https://github.com/PreMiD/Presences/issues/763

**Comment by SlowLife1661** [comment]
Maybe use the `time-info style-scope ytmusic-player-bar` instead

**Comment by SlowLife1661** [comment]
In Presence code yes
 ```ts
 const video = document.querySelector("video");
 const [elapsed2, duration2]  = document.querySelector("span.time-info.style-scope.ytmusic-player-bar")?.textContent?.padEnd(2)?.split(" / ");
    
 console.clear();
 console.log(`Cache: ${~~video.currentTime} / ${~~video.duration}`);
 console.log(`Progress: ${presence.timestampFromFormat(elapsed2)} / ${presence.timestampFromFormat(duration2)}`);
 ```

**Comment by ACertainCoder** [comment]
What? Why? You can simply use `document​.​querySelector​(​"#progress-bar").value` and `document​.​querySelector​(​"#progress-bar").max` instead as already said. That would be way less code. 🤷‍♂️

**Comment by SlowLife1661** [comment]
bruh right it's same anyway

**Comment by EncryptedDev** [comment]
Cannot reproduce such issue at the time of writing this, most likely fixed in #4197

**Comment by ACertainCoder** [comment]
Still reproducable.
https://imgur.com/vYhNeip
As said already, this issue only occurs if you are subscribed YouTube (Music) Premium.
